/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sortproperties;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.stream.Collectors;

import sortproperties.service.PropertyService;
import sortproperties.service.impl.PropertyAddNewLinesService;
import sortproperties.service.impl.PropertySortingService;

public class App {

    public static void main(String[] args) throws IOException {
        List<PropertyService> propertyServices = new ArrayList<>();
        // add new lines in first
        propertyServices.add(new PropertyAddNewLinesService());
        // then sort
        propertyServices.add(new PropertySortingService());

        try (InputStream is = App.class.getClassLoader().getResourceAsStream("application.properties")) {
            Properties prop = new Properties();
            prop.load(is);

            Path path = Paths.get(prop.getProperty("messages.path"));
            List<Path> allMessages = Files.list(path).filter(p -> p.toString().contains("messages")).collect(Collectors.toList());
            allMessages.forEach(messagesPath -> propertyServices.forEach(p -> p.execute(messagesPath)));
            System.out.println("done!");
        }
    }
}
